config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'users#index'

  get '/users', to: 'users#index', as: "users"
  get '/libraries', to: 'libraries#index'
  get '/users/new', to: 'users#new', as: 'new_user'
  get '/libraries/new', to: 'libraries#new', as: 'new_library'
  post '/users', to: 'users#create'
  post 'libraries', to: 'libraries#create'
  get '/libraries/:id', to: 'libraries#show', as: 'library'
  get '/libraries/:id/edit', to: 'libraries#edit', as: 'edit_libraries'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_users'
  get '/users/:id', to: 'users#show', as: "user"
  get '/users/:user_id/libraries', to: 'library_users#index', as: 'user_libraries'
  post '/libraries/:library_id/users', to: 'library_users#create', as: 'library_users'
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  post '/sessions', to: 'sessions#create'
  patch '/libraries/:id', to: 'libraries#update'
  patch '/users/:id', to: 'users#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/library.rb
class Library < ApplicationRecord
  has_many :library_users, dependent: :destroy
  has_many :users, through: :library_users
end

app/models/library_user.rb
class LibraryUser < ApplicationRecord
  belongs_to :user
  belongs_to :library
end

app/models/user.rb
class User < ApplicationRecord
  has_many :library_users, dependent: :destroy
  has_many :libraries, through: :library_users
  has_secure_password

  def self.confirm(params)
    @user = User.find_by({email: params[:email]})
    @user ? @user.authenticate(params[:password]) : false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper


end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  def index
    @libraries = Library.all
  end

  def new
    @library = Library.new
  end

  def create
    @library = Library.create(library_params)
    redirect_to library_path(library)
  end

  def show
    library_id = params[:id]
    @library = Library.find_by_id(library_id)
  end

  def edit
    library_id = params[:id]

    @library = Library.find_by_id(library_id)
  end

  def update
    library_id = params[:id]
    library = Library.find_by_id(library_id)
    library.update_attributes(library_params)
    redirect_to library_path(library)
  end
  private

  def library_params
    params.require(:library).permit(:name, :floor_count, :floor_area)
  end
end

app/controllers/library_users_controller.rb
class LibraryUsersController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @libraries = @user.libraries
  end

  def create
    @library = Library.find(params[:library_id])
    @library.users.push(current_user)

    redirect_to current_user
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:email, :password)
    @user = User.confirm(user_params)
    if @user
      login(@user)
      flash[:notice] = "Successfully logged in."
      redirect_to @user
    else
      flash[:error] = "Incorrect email or password"
      redirect_to login_path
    end
  end
    def destroy
      session[:user_id] = nil
      flash[:notice] = "Successfully logged out."
      redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in?, only: [:show]

  def index
    @users= User.all
  end

  def create
    @user = User.create(user_params)
    login(@user)
    redirect_to @user
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    user_id = params[:id]

    @user = User.find_by_id(user_id)
  end

  def update
    user_id = params[:id]

    @user = User.find_by_id(user_id)

    @user.update_attributes(user_params)
    redirect_to @user
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/helpers/library_users_helper.rb
module LibraryUsersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def logout(user)
    @current_user = session[:user_id] = nil
  end

  def logged_in?
    if current_user == nil
      redirect_to new_session_path
    end
  end

  def current_user
    @current_user || User.find_by_id(session[:user_id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LibraryApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul>
      <% if current_user %>
        <li><%= link_to "Profile", user_path(current_user) %></li>
        <li><%= link_to "Log Out", logout_path  %></li>
      <% else %>
        <li><%= link_to "Create Account", new_user_path %></li>
        <li><%= link_to "Log In", login_path %></li>
      <% end %>
    </ul>

    <% flash.each do |name, msg| %>
      <p>
        <small> <%= name.capitalize %>: <%= msg %> </small>
      </p>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/libraries/edit.html.erb
<%= form_for @library do |f| %>
  <div>
    <%= f.text_field :name, placeholder: "Name" %>
  </div>
  <div>
    <%= f.number_field :floor_count, placeholder: "Floor Count" %>
  </div>
  <div>
    <%= f.number_field :floor_area, placeholder: "Floor Area" %>
  </div>
  <%= f.submit "Save Library" %>
<% end %>

app/views/libraries/index.html.erb
<% @libraries.each do |library| %>
  <div>
      <h3><%= library.name %></h3>
      <% if current_user %>
        <%= button_to "Join", library_users_path(library) %>
      <% end %>
    </div>
    <br>
  <% end %>

app/views/libraries/new.html.erb
<%= form_for @library do |f| %>
  <div>
    <%= f.text_field :name, placeholder: "Name" %>
  </div>
  <div>
    <%= f.number_field :floor_count, placeholder: "Floor Count" %>
  </div>
  <div>
    <%= f.number_field :floor_area, placeholder: "Floor Area" %>
  </div>
  <%= f.submit %>
<% end %>

app/views/libraries/show.html.erb
<h1><%= @library.name %></h1>
<p><%= @library.floor_count %></p>

app/views/library_users/index.html.erb
<div><%= @user.first_name %> is a member of the following libraries</div>

<ul>
  <% @libraries.each do |lib| %>
    <li><%= lib.name %></li>
  <% end %>
</ul>

app/views/users/edit.html.erb
<%= form_for @user do |f| %>
  <div>
    <%= f.text_field :first_name, placeholder: "First Name" %>
  </div>
  <div>
    <%= f.text_field :last_name, placeholder: "Last Name" %>
  </div>
  <div>
    <%= f.text_field :email, placeholder: "Email" %>
  </div>

  <%= f.submit "Save User" %>
<% end %>

app/views/users/index.html.erb
<h1> Welcome to the Users Index. </h1>

<div>
  There are currently <%= @users.length %> user(s) signed up!

</div>

<% @users.each do |user| %>
  <p>
    <strong>Name:</strong> <%= user.first_name %><br>
    <strong>Email:</strong> <%= user.email %>
  </p>
<% end %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <div>
    <%= f.text_field :first_name, placeholder: "First Name" %>
  </div>
  <div>
    <%= f.text_field :last_name, placeholder: "Last Name" %>
  </div>
  <div>
    <%= f.text_field :email, placeholder: "Email" %>
  </div>
  <div>
    <%= f.password_field :password, placeholder: "Password" %>
  </div>
  <%= f.submit "Sign Up" %>
<% end %>

app/views/users/show.html.erb
<div>
  Welcome, <%= @user.first_name %> !
</div>